[[constraint]]
  name = "github.com/cloudfoundry-community/go-cfenv"
  version = "1.17.0"

[[constraint]]
  name = "github.com/bgentry/que-go"
  source = "github.com/govau/que-go"
  branch = "fixshutdown" # fixes shutdown by signal

[[constraint]]
  name = "github.com/google/certificate-transparency-go"
  source = "github.com/govau/certificate-transparency-go"
  branch = "objecthash" # adds objecthash support

[[constraint]]
  branch = "master"
  name = "github.com/continusec/verifiabledatastructures"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/jackc/pgx"
  version = "3.1.0"

[prune]
  go-tests = true
  unused-packages = true
