---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: govau/cga-cf-bosh-cli
    tag: latest

inputs:
- name: src

outputs:
- name: build

caches:
- path: pkg/dep/sources

run:
  path: src/ci/build.sh
