// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	metadata.proto

It has these top-level messages:
	LogMetadata
	SignedTreeHead
	AddResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogMetadata struct {
	Id            []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PrivateKeyDer []byte `protobuf:"bytes,2,opt,name=private_key_der,json=privateKeyDer,proto3" json:"private_key_der,omitempty"`
}

func (m *LogMetadata) Reset()                    { *m = LogMetadata{} }
func (m *LogMetadata) String() string            { return proto.CompactTextString(m) }
func (*LogMetadata) ProtoMessage()               {}
func (*LogMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LogMetadata) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *LogMetadata) GetPrivateKeyDer() []byte {
	if m != nil {
		return m.PrivateKeyDer
	}
	return nil
}

type SignedTreeHead struct {
	TreeSize          int64  `protobuf:"varint,1,opt,name=tree_size,json=treeSize" json:"tree_size,omitempty"`
	Timestamp         int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Sha256RootHash    []byte `protobuf:"bytes,3,opt,name=sha256_root_hash,json=sha256RootHash,proto3" json:"sha256_root_hash,omitempty"`
	TreeHeadSignature []byte `protobuf:"bytes,4,opt,name=tree_head_signature,json=treeHeadSignature,proto3" json:"tree_head_signature,omitempty"`
}

func (m *SignedTreeHead) Reset()                    { *m = SignedTreeHead{} }
func (m *SignedTreeHead) String() string            { return proto.CompactTextString(m) }
func (*SignedTreeHead) ProtoMessage()               {}
func (*SignedTreeHead) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SignedTreeHead) GetTreeSize() int64 {
	if m != nil {
		return m.TreeSize
	}
	return 0
}

func (m *SignedTreeHead) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SignedTreeHead) GetSha256RootHash() []byte {
	if m != nil {
		return m.Sha256RootHash
	}
	return nil
}

func (m *SignedTreeHead) GetTreeHeadSignature() []byte {
	if m != nil {
		return m.TreeHeadSignature
	}
	return nil
}

type AddResponse struct {
	Timestamp int64  `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *AddResponse) Reset()                    { *m = AddResponse{} }
func (m *AddResponse) String() string            { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()               {}
func (*AddResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *AddResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*LogMetadata)(nil), "au.gov.digital.verifiabledatastructures.LogMetadata")
	proto.RegisterType((*SignedTreeHead)(nil), "au.gov.digital.verifiabledatastructures.SignedTreeHead")
	proto.RegisterType((*AddResponse)(nil), "au.gov.digital.verifiabledatastructures.AddResponse")
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0x5a, 0xc4, 0x6e, 0x35, 0xea, 0x7a, 0x09, 0xd8, 0x83, 0xf4, 0xa0, 0x3d, 0xe5,
	0xa0, 0xe8, 0x5d, 0x51, 0xa8, 0xa8, 0x97, 0xd4, 0x93, 0x97, 0x65, 0xe2, 0x8e, 0xc9, 0x60, 0x93,
	0x0d, 0xbb, 0x93, 0x40, 0xfb, 0x3e, 0xbe, 0xa7, 0x64, 0x1b, 0x09, 0xf4, 0xfa, 0x9b, 0x6f, 0xbf,
	0x3f, 0x2b, 0xa2, 0x12, 0x19, 0x34, 0x30, 0x24, 0xb5, 0x35, 0x6c, 0xe4, 0x35, 0x34, 0x49, 0x6e,
	0xda, 0x44, 0x53, 0x4e, 0x0c, 0xeb, 0xa4, 0x45, 0x4b, 0xdf, 0x04, 0xd9, 0x1a, 0x3b, 0x91, 0x63,
	0xdb, 0x7c, 0x71, 0x63, 0xd1, 0xcd, 0x9f, 0xc5, 0xf4, 0xcd, 0xe4, 0xef, 0xfd, 0x6b, 0x19, 0x89,
	0x90, 0x74, 0x1c, 0x5c, 0x06, 0x8b, 0xa3, 0x34, 0x24, 0x2d, 0xaf, 0xc4, 0x49, 0x6d, 0xa9, 0x05,
	0x46, 0xf5, 0x83, 0x1b, 0xa5, 0xd1, 0xc6, 0xa1, 0x3f, 0x1e, 0xf7, 0xf8, 0x15, 0x37, 0x4f, 0x68,
	0xe7, 0xbf, 0x81, 0x88, 0x56, 0x94, 0x57, 0xa8, 0x3f, 0x2c, 0xe2, 0x12, 0x41, 0xcb, 0x0b, 0x31,
	0x61, 0x8b, 0xa8, 0x1c, 0x6d, 0xd1, 0x3b, 0x8e, 0xd2, 0xc3, 0x0e, 0xac, 0x68, 0x8b, 0x72, 0x26,
	0x26, 0x4c, 0x25, 0x3a, 0x86, 0xb2, 0xf6, 0x8e, 0xa3, 0x74, 0x00, 0x72, 0x21, 0x4e, 0x5d, 0x01,
	0x37, 0x77, 0xf7, 0xca, 0x1a, 0xc3, 0xaa, 0x00, 0x57, 0xc4, 0x23, 0x1f, 0x1b, 0xed, 0x78, 0x6a,
	0x0c, 0x2f, 0xc1, 0x15, 0x32, 0x11, 0xe7, 0x3e, 0xa4, 0x40, 0xd0, 0xca, 0x51, 0x5e, 0x41, 0x37,
	0x2b, 0x1e, 0x7b, 0xf1, 0x19, 0xf7, 0x5d, 0x56, 0xff, 0x87, 0xf9, 0x8b, 0x98, 0x3e, 0x68, 0x9d,
	0xa2, 0xab, 0x4d, 0xe5, 0xf6, 0x6a, 0x04, 0xfb, 0x35, 0x66, 0x62, 0x32, 0x58, 0xee, 0x66, 0x0f,
	0xe0, 0x71, 0xfc, 0x19, 0xd6, 0x59, 0x76, 0xe0, 0xff, 0xfb, 0xf6, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x51, 0xa9, 0xa6, 0xe9, 0x81, 0x01, 0x00, 0x00,
}
